---
name: RRD-Tweak
version: 0.02
author:
  - 'Stanislav Sinyagin <ssinyagin@k-open.com>'
abstract: RRD file manipulation
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
build_requires:
  Data::Compare: 0
  Data::Dumper: 0
  ExtUtils::CBuilder: 0
  RRDs: 0
  Test::More: 0
requires:
  perl: v5.8.8
configure_requires:
  Module::Build: 0.340201
provides:
  RRD::Tweak:
    file: lib/RRD/Tweak.pm
    version: 0.02
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
